//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriemPacientov
    {
        public int id { get; set; }
        public int PacientID { get; set; }
        public int DoctorID { get; set; }
        public string Specialnost { get; set; }
        public System.DateTime Date_of_priema { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Pachienti Pachienti { get; set; }
    }
}
